# Generated by Django 3.2 on 2021-05-26 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=564)),
                ('status', models.CharField(choices=[('open', 'open'), ('close', 'close')], default='open', max_length=9)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=564)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('Resolution', 'Resolution'), ('Update', 'Update'), ('Investigation', 'Investigation')], max_length=25)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.incident')),
            ],
        ),
    ]
