# Generated by Django 3.2 on 2021-05-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
