# Generated by Django 3.2 on 2021-05-26 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_incident_end_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Updates',
        ),
    ]
